name: Cloudflare Pages

on:
  push:
  workflow_dispatch:

env:
  VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
  VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
  VITE_REDIRECT_URI: https://truthdeck.happa8.dev/
jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: "truthdeck"
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
